"use client";

import { CheckCircle2, ListOrdered, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { PlannedStep } from "@/lib/types";

interface PlanReviewProps {
  rationale: string;
  steps: PlannedStep[];
  onApprove: () => void;
  onReject: () => void;
  pending?: boolean;
  usedMock: boolean;
}

export function PlanReview({
  rationale,
  steps,
  onApprove,
  onReject,
  pending,
  usedMock,
}: PlanReviewProps) {
  return (
    <Card className="overflow-hidden">
      <div className="flex items-start gap-3 border-b bg-gradient-to-r from-primary/10 via-primary/5 to-transparent p-5">
        <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/15 text-primary">
          <ListOrdered className="h-5 w-5" />
        </div>
        <div className="space-y-1">
          <p className="text-xs font-semibold uppercase tracking-wider text-primary">
            Proposed plan
          </p>
          <p className="text-sm leading-relaxed text-foreground/90">
            {rationale}
          </p>
          <p className="text-[11px] text-muted-foreground">
            Generated by the {usedMock ? "mock planner" : "live LLM provider"}.
            Approve to begin execution — no tools run until you do.
          </p>
        </div>
      </div>
      <ol className="divide-y">
        {steps.map((step) => (
          <li key={step.position} className="flex gap-4 p-4">
            <span className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-semibold">
              {step.position}
            </span>
            <div className="space-y-1.5">
              <div className="flex items-center gap-2">
                <code className="rounded bg-muted px-1.5 py-0.5 text-xs font-medium">
                  {step.tool_name}
                </code>
              </div>
              <p className="text-sm leading-relaxed text-foreground/90">
                {step.description}
              </p>
              {Object.keys(step.arguments).length > 0 && (
                <details className="text-xs text-muted-foreground">
                  <summary className="cursor-pointer select-none hover:text-foreground">
                    Show arguments
                  </summary>
                  <pre className="mt-2 max-h-44 overflow-auto rounded-lg border bg-muted/40 p-2">
                    {JSON.stringify(step.arguments, null, 2)}
                  </pre>
                </details>
              )}
            </div>
          </li>
        ))}
      </ol>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t bg-muted/30 px-5 py-4">
        <p className="text-xs text-muted-foreground">
          {steps.length} {steps.length === 1 ? "step" : "steps"} • only registered tools are executable
        </p>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={onReject}
            disabled={pending}
            className="gap-1.5"
          >
            <XCircle className="h-4 w-4" />
            Reject plan
          </Button>
          <Button
            variant="success"
            onClick={onApprove}
            disabled={pending}
            className="gap-1.5"
          >
            <CheckCircle2 className="h-4 w-4" />
            Approve & execute
          </Button>
        </div>
      </div>
    </Card>
  );
}
